language: java
jdk: oraclejdk11
services:
  - mysql
sudo: required
before_install:
  - mysql -u root -e 'CREATE DATABASE songs_database'
  - mysql -u root -e "CREATE USER 'JAVIBL8'@'localhost' IDENTIFIED BY 'practicas,IV';"
  - mysql -u root -e "GRANT ALL ON songs_database.* TO 'JAVIBL8'@'localhost';"
